---
sudo: required

language: python
python: '3.6'
services:
  - docker
rvm:
  - 2.2

install:
  - bundle install
  - pip install -r requirements.txt

script:
  # Validate README.md URLs
  - awesome_bot --skip-save-results --allow-dupe --files README.md,tests/README.md

  - yamllint --config-file=tests/yamllint.yml .

  - git clone https://github.com/mesaguy/docker ~/docker

  - bundle exec kitchen test default-oraclelinux-75
