---
- name: 'Make directories for {{ prometheus_software_name_version }} build'
  become: true
  file:
    owner: '{{ prometheus_user }}'
    group: '{{ prometheus_group }}'
    mode: 0750
    path: '{{ prometheus_build_directory }}'
    state: directory
  with_items:
    - '{{ prometheus_software_src_dir }}'
    - '{{ prometheus_software_build_dir }}'
  loop_control:
    loop_var: prometheus_build_directory

- name: 'Download and extract the {{ prometheus_software_name_version }} project source to {{ prometheus_software_build_dir }}'
  become: true
  # Certain versions of ansible break 'become_user' for 'archive' and 'get_url', supposedly fixed in 2.6.3:
  # become_user: '{% if ansible_version.full is version_compare("2.6.0", ">=") and ansible_version.full is version_compare("2.6.2", "<")  %}root{% else %}{{ prometheus_user }}{% endif %}'
  # become_user: '{{ prometheus_user }}'
  unarchive:
    extra_opts: ['--strip-components=1']
    creates: '{{ prometheus_software_src_dir }}/*'
    dest: '{{ prometheus_software_src_dir }}'
    owner: '{{ prometheus_user }}'
    group: '{{ prometheus_group }}'
    src: '{{ prometheus_software_src_url }}'
    remote_src: true
  when: prometheus_software_src_url is match('.*(tar.gz|zip)$')

- name: 'Clone the {{ prometheus_software_name_version }} project source from {{ prometheus_software_src_url }} to {{ prometheus_software_src_dir }}'
  become: true
  # become_user: '{{ prometheus_user }}'
  git:
    repo: '{{ prometheus_software_src_url }}'
    dest: '{{ prometheus_software_src_dir }}'
    version: '{{ prometheus_software_src_version | default(prometheus_software_version, true) }}'
  when: prometheus_software_src_url is not match('.*(tar.gz|zip)$')

- name: 'Gather statistics on the file {{ prometheus_software_src_dir }}/Makefile'
  become: true
  # become_user: '{{ prometheus_user }}'
  stat:
    path: '{{ prometheus_software_src_dir }}/Makefile'
  register: makefile

- name: 'Build {{ prometheus_software_name_version }} source code with Makefile'
  become: true
  # become_user: '{{ prometheus_user }}'
  shell: '{{ prometheus_software_makefile_make_command }}'
  args:
    chdir: '{{ prometheus_software_src_dir }}'
    creates: '{{ prometheus_software_name }}'
  environment:
    GOPATH: '{{ prometheus_software_build_dir }}'
    GOROOT: '{{ prometheus_go_dir }}/{{ prometheus_go_version }}'
    PATH: '{{ ansible_env.PATH }}:{{ prometheus_go_dir }}/{{ prometheus_go_version }}/bin:{{ prometheus_software_build_dir }}/bin'
  when: makefile.stat.exists == True

- name: 'Build {{ prometheus_software_name_version }} source code without Makefile'
  become: true
  # become_user: '{{ prometheus_user }}'
  shell: '{{ prometheus_software_make_command }}'
  args:
    chdir: '{{ prometheus_software_src_dir }}'
    creates: '{{ prometheus_software_name }}'
  environment:
    GOPATH: '{{ prometheus_software_build_dir }}'
    GOROOT: '{{ prometheus_go_dir }}/{{ prometheus_go_version }}'
    PATH: '{{ ansible_env.PATH }}:{{ prometheus_go_dir }}/{{ prometheus_go_version }}/bin:{{ prometheus_software_build_dir }}/bin'
  when: makefile.stat.exists == False

- name: 'Copy {{ prometheus_software_name_version }} to {{ prometheus_software_install_dir }}'
  become: true
  copy:
    remote_src: true
    src: '{{ prometheus_software_src_dir }}/{{ prometheus_built_file }}'
    dest: '{{ prometheus_software_install_dir }}'
    mode: 0555
  with_items: '{{ prometheus_software_files | default([prometheus_software_shortname], true) }}'
  loop_control:
    loop_var: prometheus_built_file
  register: prometheus_software_installation

- name: 'Cleanup {{ prometheus_software_build_dir }} directory from {{ prometheus_software_name_version }} build'
  become: true
  file:
    path: '{{ prometheus_software_build_dir }}'
    state: absent
