---
- name: Install capabilities packages
  become: true
  package:
    name: '{{ prometheus_capabilites_packages }}'
    state: present
  when: prometheus_capabilites_packages is defined and prometheus_capabilites_packages

- name: Search for 'setcap' capabilities binary
  shell: which setcap
  environment:
    PATH: '/sbin:/usr/sbin:{{ ansible_env.PATH }}'
  ignore_errors: true
  changed_when: false
  register: prometheus_software_capabilities_present

- name: Define capabilities install as complete
  set_fact:
    prometheus_capabilities_install_task_executed: true
