---
- name: Install 'sponge'
  become: true
  # Can fail in cases like EL without EPEL enabled
  ignore_errors: true
  package:
    name: '{{ prometheus_sponge_packages }}'
    state: present
  when:
    - prometheus_sponge_packages is defined
    - prometheus_install_sponge | bool

- name: Check if "sponge" is installed and in PATH
  command: which sponge
  changed_when: false
  ignore_errors: true
  register: prometheus_sponge_installed
  when:
    - prometheus_sponge_installed is undefined
    - prometheus_sponge_packages is defined

- name: Set "sponge" installed fact
  set_fact:
    prometheus_sponge_is_installed: '{% if "rc" in prometheus_sponge_installed and prometheus_sponge_installed.rc == 0 %}true{% else %}false{% endif %}'
  when:
    - prometheus_sponge_is_installed is undefined
    - prometheus_sponge_packages is defined
    - prometheus_sponge_installed is success
