---
- name: 'Install {{ prometheus_software_name_version }} specific prerequisite software'
  become: true
  package:
    name: '{{ prometheus_software_dependencies }}'
    state: present
  when: prometheus_software_dependencies is defined and prometheus_software_dependencies

- name: 'Include task to perform installation of {{ prometheus_software_name_version }} from binary'
  include_tasks: _install_from_binary.yml
  when: prometheus_software_bin_url is defined and prometheus_software_bin_url and not prometheus_always_build_from_source

- name: 'Include task to perform installation of {{ prometheus_software_name_version }} by compiling go source'
  include_tasks: _install_from_go_source.yml
  when: (prometheus_software_installation is not defined or (not prometheus_software_installation or (prometheus_software_installation.failed and (prometheus_software_fallback_to_build or prometheus_fallback_to_build)))) and prometheus_software_src_url is defined and prometheus_software_src_url

- name: Link {{ prometheus_software_install_dir }} to {{ prometheus_software_root_dir }}/active
  become: true
  file:
    state: link
    src: '{{ prometheus_software_install_dir }}'
    dest: '{{ prometheus_software_root_dir }}/active'
    force: true
    owner: '{{ prometheus_user }}'
    group: '{{ prometheus_group }}'
