---
- name: 'Include task to perform {{ prometheus_software_name_version }} fact definitions'
  include_tasks: _install_facts.yml

- name: 'Set variables for {{ prometheus_software_name_version }} binary install'
  set_fact:
    prometheus_software_binary: '{{ prometheus_software_root_dir }}/{{ prometheus_software_version }}/{{ prometheus_software_binary_name | default(prometheus_software_name, true) }}'
    prometheus_software_install_dir: '{{ prometheus_software_root_dir }}/{{ prometheus_software_version }}'

- name: 'Include task to setup directories for {{ prometheus_software_name_version }} installation'
  include_tasks: _install_directory.yml

- name: 'Unarchive {{ prometheus_software_name_version }}'
  become: true
  unarchive:
    extra_opts: '{{ prometheus_software_unarchive_opts | default(prometheus_default_unarchive_opts) }}'
    creates: '{{ prometheus_software_binary }}'
    owner: root
    group: '{{ prometheus_group }}'
    src: '{{ prometheus_software_bin_url }}'
    dest: '{{ prometheus_software_install_dir }}'
    remote_src: true
  # Handled downstream:
  ignore_errors: '{{ prometheus_software_fallback_to_build | bool }}'
  register: prometheus_software_installation
