---
- name: Include task to setup additional exporters
  include_tasks: _setup_client_tgroup.yml
  with_items: '{{ prometheus_additional_exporters }}'
  vars:
    prometheus_software_name: '{{ additional_exporter.name }}'
    prometheus_software_port: '{{ additional_exporter.port }}'
    prometheus_additional_tgroup_labels: '{{ additional_exporter.labels | default({}) }}'
    prometheus_software_tgroup_jobname: '{{ additional_exporter.name }}'
  loop_control:
    loop_var: additional_exporter
  when: prometheus_additional_exporters

- name: Include task to setup firewall rules additional exporters
  include_tasks: '_setup_firewall.yml'
  with_items: '{{ prometheus_additional_exporters }}'
  loop_control:
    loop_var: additional_exporter
  when: prometheus_client_tgroup_install is defined and prometheus_client_tgroup_install and (prometheus_manage_client_firewalld or prometheus_manage_client_iptables) and prometheus_software_port and prometheus_server_ips
