---
- name: Install {{ prometheus_software_name_version }} specific prerequisite software
  become: true
  package:
    name: '{{ prometheus_software_dependencies }}'
    state: present
  when: prometheus_software_dependencies is defined and prometheus_software_dependencies

- name: Include task to perform installation of {{ prometheus_software_name_version }} from binary
  include_tasks: _install_from_binary.yml
  when: prometheus_software_bin_url is defined and prometheus_software_bin_url and not prometheus_always_build_from_source

- name: Include task to perform installation of {{ prometheus_software_name_version }} by compiling go source
  include_tasks: _install_from_go_source.yml
  when: (prometheus_software_installation is not defined or (not prometheus_software_installation or (prometheus_software_installation.failed and (prometheus_software_fallback_to_build or prometheus_fallback_to_build)))) and prometheus_software_src_url is defined and prometheus_software_src_url

- name: Include task to symlink latest {{ prometheus_software_name_version }} directory to an "active" directory
  include_tasks: _install_active_symlink.yml

- block:
    - name: Set {{ prometheus_software_name_version }} tgroup facts
      set_fact:
        prometheus_client_fqdn: '{% if prometheus_tgroup_use_facts %}{{ ansible_fqdn }}{% else %}{{ inventory_hostname }}{% endif %}'
        prometheus_client_hostname: '{% if prometheus_tgroup_use_facts %}{{ ansible_hostname }}{% else %}{{ inventory_hostname_short }}{% endif %}'

    - name: Include task to configure {{ prometheus_software_name }} tgroup files on Prometheus servers
      include_tasks: _setup_client_tgroup.yml
  when: prometheus_servers is defined and prometheus_exporter and prometheus_manage_client_tgroups
