---
- name: Install 'sponge'
  become: true
  # Can fail in cases like EL without EPEL enabled
  ignore_errors: true
  register: prometheus_sponge_installation
  package:
    name: '{{ prometheus_sponge_packages }}'
    state: present
  when:
    - prometheus_sponge_packages is defined
    - prometheus_install_sponge | bool

- name: Check for sponge in PATH
  include_tasks: _check_for_sponge.yml
