---
- name: 'Include task to setup {{ prometheus_software_name_version }} {{ ansible_service_mgr }} service'
  include_tasks: '_service_mgr_{{ ansible_service_mgr | regex_replace("^(openrc|upstart)$", "init") }}.yml'
  when: prometheus_software_service_test|bool

- name: 'Test that {{ prometheus_software_service_name }} port {{ prometheus_software_port }} is accessible (software is running)'
  wait_for:
    host: '{{ prometheus_software_host | default("0.0.0.0") }}'
    port: '{{ prometheus_software_port }}'
    connect_timeout: 10
    state: started
    timeout: 10
  when: prometheus_software_service_test|bool and prometheus_software_port_test is defined and prometheus_software_port_test|bool and prometheus_software_port
