---
- name: Include task to setup tgroup for node {{ prometheus_client_hostname }} exporters
  include_tasks: _setup_server_node_exporters_tgroup.yml
  with_items: '{{ hostvars[prometheus_client_hostname].prometheus_components }}'
  delegate_to: localhost
  connection: local
  loop_control:
    loop_var: prometheus_software_name
  when: "'prometheus_components' in hostvars[prometheus_client_hostname]"

- name: Identify additional exporters for node {{ prometheus_client_hostname }}
  set_fact:
    prometheus_additional_exporters: '{{ hostvars[prometheus_client_hostname].prometheus_additional_exporters }}'
    prometheus_server_tgroup_install: true
  when: "'prometheus_additional_exporters' in hostvars[prometheus_client_hostname]"

- name: Setup additional exporters for node {{ prometheus_client_hostname }}
  include_role:
    name: mesaguy.prometheus
    tasks_from: _install_additional_exporters.yml
  when: prometheus_additional_exporters is defined and prometheus_additional_exporters

- name: Unset additional exporters variables
  set_fact:
    prometheus_additional_exporters: {}
