---
- name: Check portage manifest present
  stat:
    path: /usr/portage/Manifest
  register: portage_manifest

- name: Run the equivalent of 'emerge-webrsync'
  become: true
  portage:
    sync: web
  register: prometheus_emerge_update
  retries: 5
  delay: 10
  until: prometheus_emerge_update is succeeded
  when: not portage_manifest.stat.exists
