---
- name: Merge any additional labels into global tgroup labels
  set_fact:
    prometheus_tgroup_labels: '{{ prometheus_tgroup_labels | combine(prometheus_additional_tgroup_labels | default({})) }}'

- name: 'Create managed tgroup directory: {{ prometheus_managed_tgroup_dir }}'
  become: true
  delegate_to: '{{ prometheus_server_name }}'
  run_once: true
  file:
    path: '{{ prometheus_managed_tgroup_dir }}'
    state: directory
    owner: '{{ prometheus_tgroup_owner }}'
    group: '{{ prometheus_tgroup_group }}'
    mode: '{{ prometheus_tgroup_mode }}'
  loop_control:
    loop_var: prometheus_server_name
  with_items: '{{ prometheus_servers }}'
  when: prometheus_tgroup_dir != prometheus_managed_tgroup_dir

- name: 'Create {{ prometheus_software_name }} tgroup file'
  become: true
  delegate_to: '{{ prometheus_server_name }}'
  template:
    src: ../templates/tgroup_host.yml.j2
    dest: '{{ prometheus_managed_tgroup_dir }}/{{ prometheus_client_hostname }}-{{ prometheus_software_name }}.yml'
    owner: root
    group: '{{ prometheus_group }}'
    mode: '0644'
  loop_control:
    loop_var: prometheus_server_name
  with_items: '{{ prometheus_servers }}'
