---
- name: Check pacman core index present
  stat:
    path: /var/lib/pacman/sync/core.db
  register: pacman_core_index

- name: Run the equivalent of 'pacman -Sy'
  become: true
  pacman:
    update_cache: true
  when: pacman_core_index.stat.exists == False
