---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Starting gluster_exporter (ofesseler) install
  set_fact:
    prometheus_exporter: true
    prometheus_gluster_exporter_ofesseler_default_port: 9189
    prometheus_software_binary_name: gluster_exporter
    prometheus_software_extra_opts: '{{ prometheus_gluster_exporter_ofesseler_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_gluster_exporter_ofesseler_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_makefile_make_command: 'go get -d && make promu && make build'
    prometheus_software_name: gluster_exporter_ofesseler
    prometheus_software_version: '{{ prometheus_gluster_exporter_ofesseler_version | default("0.2.7") }}'
    prometheus_software_src_version: '{{ prometheus_gluster_exporter_ofesseler_src_version | default("v0.2.7") }}'
    prometheus_software_description: 'Prometheus gluster_exporter (ofesseler), exporter of host statistics'
    prometheus_software_documentation: 'https://github.com/ofesseler/gluster_exporter/blob/master/README.md'
    prometheus_software_host: '{{ prometheus_gluster_exporter_ofesseler_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_gluster_exporter_ofesseler_port | default(9189) }}'
    prometheus_software_runas: '{{ prometheus_gluster_exporter_ofesseler_runas | default(prometheus_user) }}'
    prometheus_software_shortname: gluster_exporter

- name: 'Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts'
  set_fact:
    prometheus_software_opts:
      - '-listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/ofesseler/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/ofesseler/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/ofesseler/{{ prometheus_software_shortname }}.git'

- name: 'Include task to perform installation of {{ prometheus_software_name_version }}'
  include_tasks: _install.yml

- name: 'Include task to setup {{ prometheus_software_name_version }} service'
  include_tasks: _service.yml

- name: 'Include task to perform post install cleanup of {{ prometheus_software_name_version }}'
  include_tasks: _post_install_cleanup.yml
