---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include keepalived_exporter (gen2brain) variable file
  include_vars: exporters/keepalived_exporter_gen2brain.yml

- name: Starting keepalived_exporter (gen2brain) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'keepalived_exporter'
    prometheus_software_env_vars: '{{ prometheus_keepalived_exporter_gen2brain_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_keepalived_exporter_gen2brain_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_keepalived_exporter_gen2brain_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'keepalived_exporter_gen2brain'
    prometheus_software_version: '{{ prometheus_keepalived_exporter_gen2brain_version | default("0.3.0") }}'
    prometheus_software_src_version: '{{ prometheus_keepalived_exporter_gen2brain_src_version | default("0.3.0") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_keepalived_exporter_gen2brain_jobname | default("keepalived") }}'
    prometheus_software_description: 'Prometheus keepalived_exporter (gen2brain), exporter for Keepalived metrics'
    prometheus_software_documentation: 'https://github.com/gen2brain/keepalived_exporter'
    prometheus_software_host: '{{ prometheus_keepalived_exporter_gen2brain_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_keepalived_exporter_gen2brain_port | default(9650) }}'
    prometheus_software_runas: '{{ prometheus_keepalived_exporter_gen2brain_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'keepalived_exporter'
    prometheus_software_opts: []

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/gen2brain/{{ prometheus_software_shortname }}/releases/download/{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}-{{ prometheus_architecture | replace("linux-amd64", "amd64") }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/gen2brain/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/gen2brain/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
