---
- name: Ensure at least one prometheus component has been specified for {{ ansible_hostname | default(inventory_hostname) }}
  fail:
    msg: "No 'prometheus_components' variable (array) has been specified for {{ ansible_hostname | default(inventory_hostname) }}"
  when: prometheus_components is not defined or not prometheus_components

- name: Run prometheus component installation and setup tasks
  include_role:
    name: mesaguy.prometheus
    tasks_from: '{{ prometheus_component }}'
  loop_control:
    loop_var: prometheus_component
  with_items: '{{ prometheus_components }}'

- name: Setup additional exporters
  include_role:
    name: mesaguy.prometheus
    tasks_from: _install_additional_exporters.yml
  when: prometheus_additional_exporters is defined and prometheus_additional_exporters
