---
- name: Run prometheus component installation and setup tasks
  include_role:
    name: mesaguy.prometheus
    tasks_from: '{{ prometheus_component }}'
  loop_control:
    loop_var: prometheus_component
  with_items: '{{ prometheus_components }}'

- name: Setup additional exporters
  include_role:
    name: mesaguy.prometheus
    tasks_from: _install_additional_exporters.yml
  when: prometheus_additional_exporters is defined and prometheus_additional_exporters
