---
- name: Run prometheus component installation and setup tasks
  include_role:
    name: mesaguy.prometheus
    tasks_from: '{{ prometheus_component }}'
  loop_control:
    loop_var: prometheus_component
  with_items: '{{ prometheus_components }}'
