---
- block:
  - name: 'Include role mesaguy.prometheus setup task'
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: 'Starting node_exporter install'
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'node_exporter'
    prometheus_software_env_vars: '{{ prometheus_node_exporter_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_node_exporter_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_node_exporter_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_makefile_make_command: 'make build'
    prometheus_software_name: 'node_exporter'
    prometheus_software_version: '{{ prometheus_node_exporter_version | default("0.16.0") }}'
    prometheus_software_src_version: '{{ prometheus_node_exporter_src_version | default("v0.16.0") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_node_exporter_jobname | default("node") }}'
    prometheus_software_description: 'Prometheus node_exporter, exporter of host statistics'
    prometheus_software_documentation: 'https://github.com/prometheus/node_exporter'
    prometheus_node_exporter_textfiles_directory: '{{ prometheus_node_exporter_textfiles_dir | default(prometheus_etc_dir + "/node_exporter_textfiles") }}'
    prometheus_software_host: '{{ prometheus_node_exporter_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_node_exporter_port | default(9100) }}'
    prometheus_software_runas: '{{ prometheus_node_exporter_runas | default(prometheus_user) }}'

- name: 'Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts'
  set_fact:
    prometheus_software_opts:
      - '--collector.textfile.directory={{ prometheus_node_exporter_textfiles_directory }}'
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/prometheus/{{ prometheus_software_name }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_name }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/prometheus/{{ prometheus_software_name }}'
    prometheus_software_src_url: 'https://github.com/prometheus/{{ prometheus_software_name }}.git'

- name: 'Create {{ prometheus_software_name_version }} textfile directory: {{ prometheus_node_exporter_textfiles_directory }}'
  become: true
  file:
    path: '{{ prometheus_node_exporter_textfiles_directory }}'
    owner: '{{ prometheus_user }}'
    group: '{{ prometheus_group }}'
    mode: 0775
    state: directory

- name: 'Include task to perform installation of {{ prometheus_software_name_version }}'
  include_tasks: _install.yml

- name: 'Include task to setup {{ prometheus_software_name_version }} service'
  include_tasks: _service.yml

- name: 'Include task to perform post install cleanup of {{ prometheus_software_name_version }}'
  include_tasks: _post_install_cleanup.yml
