---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Starting proxysql_exporter (percona) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: proxysql_exporter
    prometheus_software_makefile_make_command: 'go get -d && go build'
    prometheus_software_name: proxysql_exporter_percona
    prometheus_software_description: 'Prometheus proxysql_exporter (percona), exporter of ProxySQL statistics'
    prometheus_software_documentation: 'https://github.com/percona/proxysql_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_url: 'https://github.com/percona/{{ prometheus_software_binary_name }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_binary_name }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/percona/{{ prometheus_software_binary_name }}'
    prometheus_software_src_url: 'https://github.com/percona/{{ prometheus_software_binary_name }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
