---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Starting script_exporter (adhocteam) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: script_exporter
    prometheus_software_makefile_make_command: 'go get -d && make build'
    prometheus_software_name: script_exporter_adhocteam
    prometheus_software_description: 'Prometheus script_exporter (adhocteam), exporter for Script metrics'
    prometheus_software_documentation: 'https://github.com/adhocteam/script_exporter'
    # Defined by prometheus_script_exporter_adhocteam_cfgs:
    prometheus_software_opts: []

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_url: 'https://github.com/adhocteam/{{ prometheus_software_binary_name }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_binary_name }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/adhocteam/{{ prometheus_software_binary_name }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include tasks to perform individual {{ prometheus_software_name_version }} configurations
  include_tasks: _install_instance.yml
  loop_control:
    loop_var: installer_instance
  loop: '{{ prometheus_script_exporter_adhocteam_cfgs }}'

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
