---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Starting zookeeper_exporter (infonova) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: zookeeper_exporter
    prometheus_software_name: zookeeper_exporter_infonova
    prometheus_software_description: 'Prometheus zookeeper_exporter (infonova), exporter of Apache ZooKeeper metrics'
    prometheus_software_documentation: 'https://github.com/infonova/zookeeper_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_src_dir_suffix: '/src/github.com/infonova/{{ prometheus_software_binary_name }}'
    prometheus_software_src_url: 'https://github.com/infonova/{{ prometheus_software_binary_name }}/archive/{{ prometheus_software_version }}.tar.gz'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
