name: kitchen tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Pacify CentOS 8.x
      run: |
        sudo mkdir -p /usr/libexec
        sudo ln -s /usr/bin/python /usr/libexec/platform-python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --upgrade-strategy=only-if-needed
        pipenv install ansible
        pipenv install

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Run kitchen tests
      run: |
        mkdir -m 0700 -p .kitchen
        if ! [ -f ".kitchen/docker_id_rsa" ] ; then ssh-keygen -f .kitchen/docker_id_rsa -t rsa -N ''; fi ; fi
        bundle exec kitchen test default-centos-83
